/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_afiicher_st (void)
{
  GtkWidget *afiicher_st;
  GtkWidget *fixed1;
  GtkWidget *notebook1;
  GtkWidget *fixed2;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1_st;
  GtkWidget *modifier_st;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *label5;
  GtkWidget *ajouter_st;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image3;
  GtkWidget *label4;
  GtkWidget *actualiser_st;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image2;
  GtkWidget *label3;
  GtkWidget *entre_rechercher_st;
  GtkWidget *chercher_st;
  GtkWidget *image6;
  GtkWidget *supprimer_st;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image5;
  GtkWidget *label6;
  GtkWidget *label30_st;
  GtkWidget *label1;
  GtkWidget *empty_notebook_page;
  GtkWidget *label2;
  GtkWidget *image1;

  afiicher_st = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (afiicher_st), _("afficher"));
  gtk_window_set_position (GTK_WINDOW (afiicher_st), GTK_WIN_POS_CENTER);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (afiicher_st), fixed1);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed1), notebook1, 0, 136);
  gtk_widget_set_size_request (notebook1, 1008, 648);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed2), scrolledwindow1, 0, 72);
  gtk_widget_set_size_request (scrolledwindow1, 832, 544);

  treeview1_st = gtk_tree_view_new ();
  gtk_widget_show (treeview1_st);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1_st);

  modifier_st = gtk_button_new ();
  gtk_widget_show (modifier_st);
  gtk_fixed_put (GTK_FIXED (fixed2), modifier_st, 840, 288);
  gtk_widget_set_size_request (modifier_st, 160, 56);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (modifier_st), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-properties", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox3), label5, FALSE, FALSE, 0);

  ajouter_st = gtk_button_new ();
  gtk_widget_show (ajouter_st);
  gtk_fixed_put (GTK_FIXED (fixed2), ajouter_st, 840, 216);
  gtk_widget_set_size_request (ajouter_st, 160, 56);
  gtk_button_set_focus_on_click (GTK_BUTTON (ajouter_st), FALSE);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (ajouter_st), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox2), image3, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox2), label4, FALSE, FALSE, 0);

  actualiser_st = gtk_button_new ();
  gtk_widget_show (actualiser_st);
  gtk_fixed_put (GTK_FIXED (fixed2), actualiser_st, 840, 144);
  gtk_widget_set_size_request (actualiser_st, 160, 56);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (actualiser_st), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image2 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox1), image2, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox1), label3, FALSE, FALSE, 0);

  entre_rechercher_st = gtk_entry_new ();
  gtk_widget_show (entre_rechercher_st);
  gtk_fixed_put (GTK_FIXED (fixed2), entre_rechercher_st, 760, 16);
  gtk_widget_set_size_request (entre_rechercher_st, 232, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entre_rechercher_st), 8226);

  chercher_st = gtk_button_new ();
  gtk_widget_show (chercher_st);
  gtk_fixed_put (GTK_FIXED (fixed2), chercher_st, 712, 16);
  gtk_widget_set_size_request (chercher_st, 42, 40);

  image6 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_container_add (GTK_CONTAINER (chercher_st), image6);

  supprimer_st = gtk_button_new ();
  gtk_widget_show (supprimer_st);
  gtk_fixed_put (GTK_FIXED (fixed2), supprimer_st, 840, 360);
  gtk_widget_set_size_request (supprimer_st, 160, 56);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (supprimer_st), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image5 = gtk_image_new_from_stock ("gtk-dialog-error", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox4), image5, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox4), label6, FALSE, FALSE, 0);

  label30_st = gtk_label_new (_("<span foreground=\"blue\" ><b>Liste des produis :</b></span>"));
  gtk_widget_show (label30_st);
  gtk_fixed_put (GTK_FIXED (fixed2), label30_st, 0, 24);
  gtk_widget_set_size_request (label30_st, 128, 40);
  gtk_label_set_use_markup (GTK_LABEL (label30_st), TRUE);

  label1 = gtk_label_new (_("<span foreground=\"green\" ><b>Affichage</b></span>"));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label1);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label1), 0.5, 0.78);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label2 = gtk_label_new (_("<span foreground=\"green\" ><b>Tache 2</b></span>"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label2);
  gtk_label_set_use_markup (GTK_LABEL (label2), TRUE);

  image1 = create_pixmap (afiicher_st, "gestion-de-stock-6_o.jpg");
  gtk_widget_show (image1);
  gtk_fixed_put (GTK_FIXED (fixed1), image1, 0, 0);
  gtk_widget_set_size_request (image1, 1008, 160);

  g_signal_connect ((gpointer) treeview1_st, "row_activated",
                    G_CALLBACK (on_treeview1_st_row_activated),
                    NULL);
  g_signal_connect ((gpointer) modifier_st, "clicked",
                    G_CALLBACK (on_modifier_st_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter_st, "clicked",
                    G_CALLBACK (on_ajouter_st_clicked),
                    NULL);
  g_signal_connect ((gpointer) actualiser_st, "clicked",
                    G_CALLBACK (on_actualiser_st_clicked),
                    NULL);
  g_signal_connect ((gpointer) chercher_st, "clicked",
                    G_CALLBACK (on_chercher_st_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer_st, "clicked",
                    G_CALLBACK (on_supprimer_st_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (afiicher_st, afiicher_st, "afiicher_st");
  GLADE_HOOKUP_OBJECT (afiicher_st, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (afiicher_st, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (afiicher_st, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (afiicher_st, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (afiicher_st, treeview1_st, "treeview1_st");
  GLADE_HOOKUP_OBJECT (afiicher_st, modifier_st, "modifier_st");
  GLADE_HOOKUP_OBJECT (afiicher_st, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (afiicher_st, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (afiicher_st, image4, "image4");
  GLADE_HOOKUP_OBJECT (afiicher_st, label5, "label5");
  GLADE_HOOKUP_OBJECT (afiicher_st, ajouter_st, "ajouter_st");
  GLADE_HOOKUP_OBJECT (afiicher_st, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (afiicher_st, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (afiicher_st, image3, "image3");
  GLADE_HOOKUP_OBJECT (afiicher_st, label4, "label4");
  GLADE_HOOKUP_OBJECT (afiicher_st, actualiser_st, "actualiser_st");
  GLADE_HOOKUP_OBJECT (afiicher_st, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (afiicher_st, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (afiicher_st, image2, "image2");
  GLADE_HOOKUP_OBJECT (afiicher_st, label3, "label3");
  GLADE_HOOKUP_OBJECT (afiicher_st, entre_rechercher_st, "entre_rechercher_st");
  GLADE_HOOKUP_OBJECT (afiicher_st, chercher_st, "chercher_st");
  GLADE_HOOKUP_OBJECT (afiicher_st, image6, "image6");
  GLADE_HOOKUP_OBJECT (afiicher_st, supprimer_st, "supprimer_st");
  GLADE_HOOKUP_OBJECT (afiicher_st, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (afiicher_st, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (afiicher_st, image5, "image5");
  GLADE_HOOKUP_OBJECT (afiicher_st, label6, "label6");
  GLADE_HOOKUP_OBJECT (afiicher_st, label30_st, "label30_st");
  GLADE_HOOKUP_OBJECT (afiicher_st, label1, "label1");
  GLADE_HOOKUP_OBJECT (afiicher_st, label2, "label2");
  GLADE_HOOKUP_OBJECT (afiicher_st, image1, "image1");

  return afiicher_st;
}

GtkWidget*
create_ajouter_st (void)
{
  GtkWidget *ajouter_st;
  GtkWidget *fixed3;
  GtkWidget *entryref_st;
  GtkWidget *entrynom_st;
  GtkObject *spinbutton1_qt_st_adj;
  GtkWidget *spinbutton1_qt_st;
  GtkWidget *label7_st;
  GtkWidget *label9_st;
  GtkWidget *label8_st;
  GtkWidget *calendar1_st;
  GtkWidget *ajouterpr_st;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image8;
  GtkWidget *label13;
  GtkWidget *anuulerajout_st;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image9;
  GtkWidget *label14;
  GtkWidget *image7;
  GtkWidget *label12_st;
  GtkObject *spinbutton1_poid_adj;
  GtkWidget *spinbutton1_poid;
  GtkWidget *label11_st;
  GtkWidget *erreurref_1;
  GtkWidget *erreur_nom1;
  GtkWidget *erreur_conf1;
  GtkWidget *checkbutton1_st;
  GtkWidget *label15;
  GtkWidget *label10_st;
  GtkWidget *radiobutton1_fr;
  GSList *radiobutton1_fr_group = NULL;
  GtkWidget *radiobutton2_nr;
  GtkWidget *combobox1_categorie;

  ajouter_st = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter_st), _("ajouter"));
  gtk_window_set_position (GTK_WINDOW (ajouter_st), GTK_WIN_POS_CENTER);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (ajouter_st), fixed3);

  entryref_st = gtk_entry_new ();
  gtk_widget_show (entryref_st);
  gtk_fixed_put (GTK_FIXED (fixed3), entryref_st, 128, 232);
  gtk_widget_set_size_request (entryref_st, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryref_st), 8226);

  entrynom_st = gtk_entry_new ();
  gtk_widget_show (entrynom_st);
  gtk_fixed_put (GTK_FIXED (fixed3), entrynom_st, 128, 288);
  gtk_widget_set_size_request (entrynom_st, 208, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynom_st), 8226);

  spinbutton1_qt_st_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1_qt_st = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_qt_st_adj), 1, 0);
  gtk_widget_show (spinbutton1_qt_st);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton1_qt_st, 128, 400);
  gtk_widget_set_size_request (spinbutton1_qt_st, 208, 32);

  label7_st = gtk_label_new (_("Nom Produit :"));
  gtk_widget_show (label7_st);
  gtk_fixed_put (GTK_FIXED (fixed3), label7_st, 0, 280);
  gtk_widget_set_size_request (label7_st, 112, 48);

  label9_st = gtk_label_new (_("Categorie :"));
  gtk_widget_show (label9_st);
  gtk_fixed_put (GTK_FIXED (fixed3), label9_st, 0, 336);
  gtk_widget_set_size_request (label9_st, 96, 40);

  label8_st = gtk_label_new (_("refernce :"));
  gtk_widget_show (label8_st);
  gtk_fixed_put (GTK_FIXED (fixed3), label8_st, 0, 232);
  gtk_widget_set_size_request (label8_st, 88, 40);

  calendar1_st = gtk_calendar_new ();
  gtk_widget_show (calendar1_st);
  gtk_fixed_put (GTK_FIXED (fixed3), calendar1_st, 464, 384);
  gtk_widget_set_size_request (calendar1_st, 162, 186);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1_st),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  ajouterpr_st = gtk_button_new ();
  gtk_widget_show (ajouterpr_st);
  gtk_fixed_put (GTK_FIXED (fixed3), ajouterpr_st, 328, 688);
  gtk_widget_set_size_request (ajouterpr_st, 200, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (ajouterpr_st), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image8 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox5), image8, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("    Ajouter"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox5), label13, FALSE, FALSE, 0);

  anuulerajout_st = gtk_button_new ();
  gtk_widget_show (anuulerajout_st);
  gtk_fixed_put (GTK_FIXED (fixed3), anuulerajout_st, 104, 688);
  gtk_widget_set_size_request (anuulerajout_st, 200, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (anuulerajout_st), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image9 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox6), image9, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("     Annuler"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox6), label14, FALSE, FALSE, 0);

  image7 = create_pixmap (ajouter_st, "index.jpeg");
  gtk_widget_show (image7);
  gtk_fixed_put (GTK_FIXED (fixed3), image7, 384, 0);
  gtk_widget_set_size_request (image7, 256, 216);

  label12_st = gtk_label_new (_("Type de stockage :"));
  gtk_widget_show (label12_st);
  gtk_fixed_put (GTK_FIXED (fixed3), label12_st, 0, 504);
  gtk_widget_set_size_request (label12_st, 144, 40);

  spinbutton1_poid_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1_poid = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_poid_adj), 1, 0);
  gtk_widget_show (spinbutton1_poid);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton1_poid, 128, 456);
  gtk_widget_set_size_request (spinbutton1_poid, 208, 32);

  label11_st = gtk_label_new (_("Date d'expiration"));
  gtk_widget_show (label11_st);
  gtk_fixed_put (GTK_FIXED (fixed3), label11_st, 480, 344);
  gtk_widget_set_size_request (label11_st, 136, 33);

  erreurref_1 = gtk_label_new (_("<span foreground=\"red\" ><b>entrer la reference !</b></span>\n"));
  gtk_widget_show (erreurref_1);
  gtk_fixed_put (GTK_FIXED (fixed3), erreurref_1, 352, 232);
  gtk_widget_set_size_request (erreurref_1, 136, 32);
  gtk_label_set_use_markup (GTK_LABEL (erreurref_1), TRUE);

  erreur_nom1 = gtk_label_new (_("<span foreground=\"red\" ><b>entre le Nom !</b></span>\n"));
  gtk_widget_show (erreur_nom1);
  gtk_fixed_put (GTK_FIXED (fixed3), erreur_nom1, 344, 296);
  gtk_widget_set_size_request (erreur_nom1, 120, 32);
  gtk_label_set_use_markup (GTK_LABEL (erreur_nom1), TRUE);

  erreur_conf1 = gtk_label_new (_("<span foreground=\"red\" ><b>confirmer STP !!</b></span>"));
  gtk_widget_show (erreur_conf1);
  gtk_fixed_put (GTK_FIXED (fixed3), erreur_conf1, 88, 576);
  gtk_widget_set_size_request (erreur_conf1, 136, 24);
  gtk_label_set_use_markup (GTK_LABEL (erreur_conf1), TRUE);

  checkbutton1_st = gtk_check_button_new_with_mnemonic (_("Confirmer l'ajout de ce Produit"));
  gtk_widget_show (checkbutton1_st);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton1_st, 56, 608);
  gtk_widget_set_size_request (checkbutton1_st, 296, 24);

  label15 = gtk_label_new (_("Poid en kg"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed3), label15, 8, 456);
  gtk_widget_set_size_request (label15, 80, 32);

  label10_st = gtk_label_new (_("Quantite :"));
  gtk_widget_show (label10_st);
  gtk_fixed_put (GTK_FIXED (fixed3), label10_st, 0, 392);
  gtk_widget_set_size_request (label10_st, 88, 48);

  radiobutton1_fr = gtk_radio_button_new_with_mnemonic (NULL, _("Ancien"));
  gtk_widget_show (radiobutton1_fr);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton1_fr, 152, 512);
  gtk_widget_set_size_request (radiobutton1_fr, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1_fr), radiobutton1_fr_group);
  radiobutton1_fr_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1_fr));

  radiobutton2_nr = gtk_radio_button_new_with_mnemonic (NULL, _("Nouveau"));
  gtk_widget_show (radiobutton2_nr);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton2_nr, 264, 512);
  gtk_widget_set_size_request (radiobutton2_nr, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2_nr), radiobutton1_fr_group);
  radiobutton1_fr_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2_nr));

  combobox1_categorie = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1_categorie);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox1_categorie, 128, 344);
  gtk_widget_set_size_request (combobox1_categorie, 208, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_categorie), _("Legumes "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_categorie), _("Fruits "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_categorie), _("Boissons"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_categorie), _("Viande"));

  g_signal_connect ((gpointer) ajouterpr_st, "clicked",
                    G_CALLBACK (on_ajouterpr_st_clicked),
                    NULL);
  g_signal_connect ((gpointer) anuulerajout_st, "clicked",
                    G_CALLBACK (on_anuulerajout_st_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1_st, "toggled",
                    G_CALLBACK (on_checkbutton1_st_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1_fr, "toggled",
                    G_CALLBACK (on_radiobutton1_fr_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2_nr, "toggled",
                    G_CALLBACK (on_radiobutton2_nr_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter_st, ajouter_st, "ajouter_st");
  GLADE_HOOKUP_OBJECT (ajouter_st, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (ajouter_st, entryref_st, "entryref_st");
  GLADE_HOOKUP_OBJECT (ajouter_st, entrynom_st, "entrynom_st");
  GLADE_HOOKUP_OBJECT (ajouter_st, spinbutton1_qt_st, "spinbutton1_qt_st");
  GLADE_HOOKUP_OBJECT (ajouter_st, label7_st, "label7_st");
  GLADE_HOOKUP_OBJECT (ajouter_st, label9_st, "label9_st");
  GLADE_HOOKUP_OBJECT (ajouter_st, label8_st, "label8_st");
  GLADE_HOOKUP_OBJECT (ajouter_st, calendar1_st, "calendar1_st");
  GLADE_HOOKUP_OBJECT (ajouter_st, ajouterpr_st, "ajouterpr_st");
  GLADE_HOOKUP_OBJECT (ajouter_st, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (ajouter_st, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (ajouter_st, image8, "image8");
  GLADE_HOOKUP_OBJECT (ajouter_st, label13, "label13");
  GLADE_HOOKUP_OBJECT (ajouter_st, anuulerajout_st, "anuulerajout_st");
  GLADE_HOOKUP_OBJECT (ajouter_st, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (ajouter_st, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (ajouter_st, image9, "image9");
  GLADE_HOOKUP_OBJECT (ajouter_st, label14, "label14");
  GLADE_HOOKUP_OBJECT (ajouter_st, image7, "image7");
  GLADE_HOOKUP_OBJECT (ajouter_st, label12_st, "label12_st");
  GLADE_HOOKUP_OBJECT (ajouter_st, spinbutton1_poid, "spinbutton1_poid");
  GLADE_HOOKUP_OBJECT (ajouter_st, label11_st, "label11_st");
  GLADE_HOOKUP_OBJECT (ajouter_st, erreurref_1, "erreurref_1");
  GLADE_HOOKUP_OBJECT (ajouter_st, erreur_nom1, "erreur_nom1");
  GLADE_HOOKUP_OBJECT (ajouter_st, erreur_conf1, "erreur_conf1");
  GLADE_HOOKUP_OBJECT (ajouter_st, checkbutton1_st, "checkbutton1_st");
  GLADE_HOOKUP_OBJECT (ajouter_st, label15, "label15");
  GLADE_HOOKUP_OBJECT (ajouter_st, label10_st, "label10_st");
  GLADE_HOOKUP_OBJECT (ajouter_st, radiobutton1_fr, "radiobutton1_fr");
  GLADE_HOOKUP_OBJECT (ajouter_st, radiobutton2_nr, "radiobutton2_nr");
  GLADE_HOOKUP_OBJECT (ajouter_st, combobox1_categorie, "combobox1_categorie");

  return ajouter_st;
}

GtkWidget*
create_supprimer_st (void)
{
  GtkWidget *supprimer_st;
  GtkWidget *fixed4;
  GtkWidget *label16;
  GtkWidget *annulersupp_st;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image11;
  GtkWidget *label18;
  GtkWidget *confirmersupp_st;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image10;
  GtkWidget *label17;

  supprimer_st = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supprimer_st), _("window1"));
  gtk_window_set_position (GTK_WINDOW (supprimer_st), GTK_WIN_POS_CENTER);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (supprimer_st), fixed4);
  gtk_widget_set_size_request (fixed4, 368, 120);

  label16 = gtk_label_new (_("Confirmer la supprition ?"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed4), label16, 104, 0);
  gtk_widget_set_size_request (label16, 200, 48);

  annulersupp_st = gtk_button_new ();
  gtk_widget_show (annulersupp_st);
  gtk_fixed_put (GTK_FIXED (fixed4), annulersupp_st, 16, 80);
  gtk_widget_set_size_request (annulersupp_st, 160, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (annulersupp_st), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image11 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox8), image11, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("    annuler"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox8), label18, FALSE, FALSE, 0);

  confirmersupp_st = gtk_button_new ();
  gtk_widget_show (confirmersupp_st);
  gtk_fixed_put (GTK_FIXED (fixed4), confirmersupp_st, 208, 80);
  gtk_widget_set_size_request (confirmersupp_st, 160, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (confirmersupp_st), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image10 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox7), image10, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("   confirmer"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox7), label17, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) annulersupp_st, "clicked",
                    G_CALLBACK (on_annulersupp_st_clicked),
                    NULL);
  g_signal_connect ((gpointer) confirmersupp_st, "clicked",
                    G_CALLBACK (on_confirmersupp_st_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer_st, supprimer_st, "supprimer_st");
  GLADE_HOOKUP_OBJECT (supprimer_st, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (supprimer_st, label16, "label16");
  GLADE_HOOKUP_OBJECT (supprimer_st, annulersupp_st, "annulersupp_st");
  GLADE_HOOKUP_OBJECT (supprimer_st, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (supprimer_st, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (supprimer_st, image11, "image11");
  GLADE_HOOKUP_OBJECT (supprimer_st, label18, "label18");
  GLADE_HOOKUP_OBJECT (supprimer_st, confirmersupp_st, "confirmersupp_st");
  GLADE_HOOKUP_OBJECT (supprimer_st, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (supprimer_st, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (supprimer_st, image10, "image10");
  GLADE_HOOKUP_OBJECT (supprimer_st, label17, "label17");

  return supprimer_st;
}

GtkWidget*
create_modifier_st (void)
{
  GtkWidget *modifier_st;
  GtkWidget *fixed5;
  GtkWidget *Mref_st;
  GtkObject *spinbutton11_st_adj;
  GtkWidget *spinbutton11_st;
  GtkWidget *label19;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *calendar1_dateM;
  GtkWidget *label25;
  GtkObject *spinbutton22_st_adj;
  GtkWidget *spinbutton22_st;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *Mnom_st;
  GtkWidget *annulerM_st;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image13;
  GtkWidget *label24;
  GtkWidget *modifier1_st;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image12;
  GtkWidget *label23;
  GtkWidget *image14;
  GtkWidget *erreur_nom2;
  GtkWidget *erreur_ref2;
  GtkWidget *label20;
  GtkWidget *erreur_conf2;
  GtkWidget *checkbutton11_st;
  GtkWidget *radiobutton11_st;
  GSList *radiobutton11_st_group = NULL;
  GtkWidget *radiobutton22_st;
  GtkWidget *combobox1;

  modifier_st = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier_st), _("modifier"));
  gtk_window_set_position (GTK_WINDOW (modifier_st), GTK_WIN_POS_CENTER);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (modifier_st), fixed5);

  Mref_st = gtk_entry_new ();
  gtk_widget_show (Mref_st);
  gtk_fixed_put (GTK_FIXED (fixed5), Mref_st, 128, 232);
  gtk_widget_set_size_request (Mref_st, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (Mref_st), 8226);

  spinbutton11_st_adj = gtk_adjustment_new (1, 1, 1000, 1, 10, 10);
  spinbutton11_st = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton11_st_adj), 1, 0);
  gtk_widget_show (spinbutton11_st);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton11_st, 128, 400);
  gtk_widget_set_size_request (spinbutton11_st, 208, 32);

  label19 = gtk_label_new (_("Nom Produit :"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed5), label19, 0, 280);
  gtk_widget_set_size_request (label19, 112, 48);

  label21 = gtk_label_new (_("Quantite :"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed5), label21, 0, 392);
  gtk_widget_set_size_request (label21, 88, 48);

  label22 = gtk_label_new (_("refernce :"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed5), label22, 0, 232);
  gtk_widget_set_size_request (label22, 88, 40);

  calendar1_dateM = gtk_calendar_new ();
  gtk_widget_show (calendar1_dateM);
  gtk_fixed_put (GTK_FIXED (fixed5), calendar1_dateM, 464, 384);
  gtk_widget_set_size_request (calendar1_dateM, 162, 186);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1_dateM),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  label25 = gtk_label_new (_("Type de stockage :"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed5), label25, 0, 504);
  gtk_widget_set_size_request (label25, 144, 40);

  spinbutton22_st_adj = gtk_adjustment_new (1, 1, 1000, 1, 10, 10);
  spinbutton22_st = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton22_st_adj), 1, 0);
  gtk_widget_show (spinbutton22_st);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton22_st, 128, 456);
  gtk_widget_set_size_request (spinbutton22_st, 208, 32);

  label26 = gtk_label_new (_("Date d'expiration"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed5), label26, 480, 344);
  gtk_widget_set_size_request (label26, 136, 33);

  label27 = gtk_label_new (_("Poid en kg"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed5), label27, 8, 456);
  gtk_widget_set_size_request (label27, 80, 32);

  Mnom_st = gtk_entry_new ();
  gtk_widget_show (Mnom_st);
  gtk_fixed_put (GTK_FIXED (fixed5), Mnom_st, 128, 288);
  gtk_widget_set_size_request (Mnom_st, 208, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (Mnom_st), 8226);

  annulerM_st = gtk_button_new ();
  gtk_widget_show (annulerM_st);
  gtk_fixed_put (GTK_FIXED (fixed5), annulerM_st, 104, 688);
  gtk_widget_set_size_request (annulerM_st, 200, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (annulerM_st), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image13 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox10), image13, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("     Annuler"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox10), label24, FALSE, FALSE, 0);

  modifier1_st = gtk_button_new ();
  gtk_widget_show (modifier1_st);
  gtk_fixed_put (GTK_FIXED (fixed5), modifier1_st, 328, 688);
  gtk_widget_set_size_request (modifier1_st, 200, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (modifier1_st), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image12 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox9), image12, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("    Modifier"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox9), label23, FALSE, FALSE, 0);

  image14 = create_pixmap (modifier_st, "index.jpeg");
  gtk_widget_show (image14);
  gtk_fixed_put (GTK_FIXED (fixed5), image14, 384, 0);
  gtk_widget_set_size_request (image14, 256, 216);

  erreur_nom2 = gtk_label_new (_("<span foreground=\"red\" ><b>entrer le nom !</b></span>"));
  gtk_widget_show (erreur_nom2);
  gtk_fixed_put (GTK_FIXED (fixed5), erreur_nom2, 344, 288);
  gtk_widget_set_size_request (erreur_nom2, 104, 40);
  gtk_label_set_use_markup (GTK_LABEL (erreur_nom2), TRUE);

  erreur_ref2 = gtk_label_new (_("<span foreground=\"red\" ><b>entrer la reference !</b></span>"));
  gtk_widget_show (erreur_ref2);
  gtk_fixed_put (GTK_FIXED (fixed5), erreur_ref2, 344, 232);
  gtk_widget_set_size_request (erreur_ref2, 144, 32);
  gtk_label_set_use_markup (GTK_LABEL (erreur_ref2), TRUE);

  label20 = gtk_label_new (_("Categorie :"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed5), label20, 0, 336);
  gtk_widget_set_size_request (label20, 96, 40);

  erreur_conf2 = gtk_label_new (_("<span foreground=\"red\" ><b>confirmer STP !!</b></span>"));
  gtk_widget_show (erreur_conf2);
  gtk_fixed_put (GTK_FIXED (fixed5), erreur_conf2, 104, 584);
  gtk_widget_set_size_request (erreur_conf2, 136, 16);
  gtk_label_set_use_markup (GTK_LABEL (erreur_conf2), TRUE);

  checkbutton11_st = gtk_check_button_new_with_mnemonic (_("Confirmer la modification de ce Produit"));
  gtk_widget_show (checkbutton11_st);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbutton11_st, 56, 608);
  gtk_widget_set_size_request (checkbutton11_st, 296, 24);

  radiobutton11_st = gtk_radio_button_new_with_mnemonic (NULL, _("Ancien"));
  gtk_widget_show (radiobutton11_st);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton11_st, 152, 512);
  gtk_widget_set_size_request (radiobutton11_st, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton11_st), radiobutton11_st_group);
  radiobutton11_st_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton11_st));

  radiobutton22_st = gtk_radio_button_new_with_mnemonic (NULL, _("Nouveau"));
  gtk_widget_show (radiobutton22_st);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton22_st, 280, 512);
  gtk_widget_set_size_request (radiobutton22_st, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton22_st), radiobutton11_st_group);
  radiobutton11_st_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton22_st));

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed5), combobox1, 128, 344);
  gtk_widget_set_size_request (combobox1, 208, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Legumes "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Fruits "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Boissons"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Viande"));

  g_signal_connect ((gpointer) annulerM_st, "clicked",
                    G_CALLBACK (on_annulerM_st_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier1_st, "clicked",
                    G_CALLBACK (on_modifier1_st_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton11_st, "toggled",
                    G_CALLBACK (on_checkbutton11_st_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton11_st, "toggled",
                    G_CALLBACK (on_radiobutton11_st_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton22_st, "toggled",
                    G_CALLBACK (on_radiobutton22_st_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_st, modifier_st, "modifier_st");
  GLADE_HOOKUP_OBJECT (modifier_st, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (modifier_st, Mref_st, "Mref_st");
  GLADE_HOOKUP_OBJECT (modifier_st, spinbutton11_st, "spinbutton11_st");
  GLADE_HOOKUP_OBJECT (modifier_st, label19, "label19");
  GLADE_HOOKUP_OBJECT (modifier_st, label21, "label21");
  GLADE_HOOKUP_OBJECT (modifier_st, label22, "label22");
  GLADE_HOOKUP_OBJECT (modifier_st, calendar1_dateM, "calendar1_dateM");
  GLADE_HOOKUP_OBJECT (modifier_st, label25, "label25");
  GLADE_HOOKUP_OBJECT (modifier_st, spinbutton22_st, "spinbutton22_st");
  GLADE_HOOKUP_OBJECT (modifier_st, label26, "label26");
  GLADE_HOOKUP_OBJECT (modifier_st, label27, "label27");
  GLADE_HOOKUP_OBJECT (modifier_st, Mnom_st, "Mnom_st");
  GLADE_HOOKUP_OBJECT (modifier_st, annulerM_st, "annulerM_st");
  GLADE_HOOKUP_OBJECT (modifier_st, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (modifier_st, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (modifier_st, image13, "image13");
  GLADE_HOOKUP_OBJECT (modifier_st, label24, "label24");
  GLADE_HOOKUP_OBJECT (modifier_st, modifier1_st, "modifier1_st");
  GLADE_HOOKUP_OBJECT (modifier_st, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (modifier_st, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (modifier_st, image12, "image12");
  GLADE_HOOKUP_OBJECT (modifier_st, label23, "label23");
  GLADE_HOOKUP_OBJECT (modifier_st, image14, "image14");
  GLADE_HOOKUP_OBJECT (modifier_st, erreur_nom2, "erreur_nom2");
  GLADE_HOOKUP_OBJECT (modifier_st, erreur_ref2, "erreur_ref2");
  GLADE_HOOKUP_OBJECT (modifier_st, label20, "label20");
  GLADE_HOOKUP_OBJECT (modifier_st, erreur_conf2, "erreur_conf2");
  GLADE_HOOKUP_OBJECT (modifier_st, checkbutton11_st, "checkbutton11_st");
  GLADE_HOOKUP_OBJECT (modifier_st, radiobutton11_st, "radiobutton11_st");
  GLADE_HOOKUP_OBJECT (modifier_st, radiobutton22_st, "radiobutton22_st");
  GLADE_HOOKUP_OBJECT (modifier_st, combobox1, "combobox1");

  gtk_widget_grab_focus (image14);
  return modifier_st;
}

