/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_afiicher_st (void);
GtkWidget* create_ajouter_st (void);
GtkWidget* create_supprimer_st (void);
GtkWidget* create_modifier_st (void);
